<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>OpExec.OnePassword</AssemblyName>
    <RootNamespace>OpExec.OnePassword</RootNamespace>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>embedded</DebugType>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>embedded</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CliWrap" Version="3.10.5" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../OpExec.SshAgent/OpExec.SshAgent.csproj" />
  </ItemGroup>
</Project>
