<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>opexec</AssemblyName>
    <RootNamespace>OpExec</RootNamespace>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>embedded</DebugType>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>embedded</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Mono.Options" Version="6.12.0.148" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../OpExec.OnePassword/OpExec.OnePassword.csproj" />
    <ProjectReference Include="../OpExec.SshAgent/OpExec.SshAgent.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="../../LICENSE.txt" LogicalName="OpExec.Licenses.OpExec.txt" />
    <EmbeddedResource Include="../../THIRD-PARTY-NOTICES.txt" LogicalName="OpExec.Licenses.ThirdPartyNotices.txt" />
  </ItemGroup>
</Project>
