<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ProductMajor>1</ProductMajor>
    <ProductRevision>12</ProductRevision>
    <Version>$(ProductMajor).$(ProductRevision).0</Version>
    <Version Condition="'$(ProductBuildLabel)' != ''">$(ProductMajor).$(ProductRevision).0-$(ProductBuildLabel)</Version>
    <AssemblyVersion>$(ProductMajor).0.0.0</AssemblyVersion>
    <FileVersion>$(ProductMajor).$(ProductRevision).0.0</FileVersion>
    <InformationalVersion>r$(ProductRevision)</InformationalVersion>
    <InformationalVersion Condition="'$(ProductBuildLabel)' != ''">r$(ProductRevision)-$(ProductBuildLabel)</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>
</Project>
